import { Component, OnInit } from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import { Chapter } from '../chapter';

@Component({
  selector: 'app-chapter',
  templateUrl: './chapter.component.html',
  styleUrls: ['./chapter.component.scss'],
})
export class ChapterComponent implements OnInit {

  chapters = [
    new Chapter(1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Ut aliquam purus sit amet luctus venenatis lectus. Sed risus ultricies tristique nulla aliquet. Quam vulputate dignissim suspendisse in est ante in nibh. Volutpat commodo sed egestas egestas. Fames ac turpis egestas integer. Purus in mollis nunc sed id semper risus in. Id aliquet risus feugiat in ante metus dictum. At tellus at urna condimentum mattis pellentesque id nibh tortor. Nec ullamcorper sit amet risus nullam eget felis eget. Congue quisque egestas diam in arcu. Lacus sed turpis tincidunt id aliquet risus feugiat in. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Neque vitae tempus quam pellentesque nec nam aliquam.\n\nDuis tristique sollicitudin nibh sit amet commodo nulla facilisi. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Suspendisse faucibus interdum posuere lorem ipsum dolor. Interdum posuere lorem ipsum dolor sit. Cursus eget nunc scelerisque viverra mauris. Lectus nulla at volutpat diam ut venenatis tellus in metus. Tempus imperdiet nulla malesuada pellentesque. Porttitor lacus luctus accumsan tortor posuere. Neque volutpat ac tincidunt vitae semper quis lectus. Ut pharetra sit amet aliquam id diam maecenas ultricies mi. Mauris augue neque gravida in. Ante in nibh mauris cursus.", "../../assets/imgs/img1.jpg"),
    new Chapter(2, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In pellentesque massa placerat duis ultricies lacus. Iaculis at erat pellentesque adipiscing commodo. Volutpat est velit egestas dui. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Venenatis tellus in metus vulputate eu scelerisque. Consequat mauris nunc congue nisi vitae suscipit tellus mauris. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Convallis posuere morbi leo urna molestie at elementum. Fames ac turpis egestas integer eget aliquet nibh praesent.\n\nScelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Amet luctus venenatis lectus magna fringilla urna porttitor. Semper quis lectus nulla at volutpat diam ut venenatis. Nibh mauris cursus mattis molestie. Odio aenean sed adipiscing diam donec adipiscing. Ultricies tristique nulla aliquet enim. Neque viverra justo nec ultrices dui sapien. At augue eget arcu dictum varius duis at. Nunc eget lorem dolor sed viverra ipsum nunc.\n\nTortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Ut lectus arcu bibendum at varius. Blandit volutpat maecenas volutpat blandit aliquam etiam. Dolor sit amet consectetur adipiscing. Eget velit aliquet sagittis id consectetur purus. Pellentesque nec nam aliquam sem et tortor consequat id. Condimentum mattis pellentesque id nibh tortor id. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Elementum eu facilisis sed odio morbi quis commodo. Non enim praesent elementum facilisis leo. Nulla facilisi morbi tempus iaculis urna. Ornare arcu odio ut sem. Accumsan sit amet nulla facilisi morbi tempus. Turpis massa tincidunt dui ut. Neque gravida in fermentum et. Euismod in pellentesque massa placerat duis ultricies lacus sed turpis. Arcu dictum varius duis at consectetur.", "../../assets/imgs/img2.jpg"),
    new Chapter(3, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Ut aliquam purus sit amet luctus venenatis lectus. Sed risus ultricies tristique nulla aliquet. Quam vulputate dignissim suspendisse in est ante in nibh. Volutpat commodo sed egestas egestas. Fames ac turpis egestas integer. Purus in mollis nunc sed id semper risus in. Id aliquet risus feugiat in ante metus dictum. At tellus at urna condimentum mattis pellentesque id nibh tortor. Nec ullamcorper sit amet risus nullam eget felis eget. Congue quisque egestas diam in arcu. Lacus sed turpis tincidunt id aliquet risus feugiat in. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Neque vitae tempus quam pellentesque nec nam aliquam./n/nDuis tristique sollicitudin nibh sit amet commodo nulla facilisi. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Suspendisse faucibus interdum posuere lorem ipsum dolor. Interdum posuere lorem ipsum dolor sit. Cursus eget nunc scelerisque viverra mauris. Lectus nulla at volutpat diam ut venenatis tellus in metus. Tempus imperdiet nulla malesuada pellentesque. Porttitor lacus luctus accumsan tortor posuere. Neque volutpat ac tincidunt vitae semper quis lectus. Ut pharetra sit amet aliquam id diam maecenas ultricies mi. Mauris augue neque gravida in. Ante in nibh mauris cursus.", "../../assets/imgs/img3.jpg"),
    new Chapter(4, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In pellentesque massa placerat duis ultricies lacus. Iaculis at erat pellentesque adipiscing commodo. Volutpat est velit egestas dui. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Venenatis tellus in metus vulputate eu scelerisque. Consequat mauris nunc congue nisi vitae suscipit tellus mauris. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Convallis posuere morbi leo urna molestie at elementum. Fames ac turpis egestas integer eget aliquet nibh praesent.\n\nScelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Amet luctus venenatis lectus magna fringilla urna porttitor. Semper quis lectus nulla at volutpat diam ut venenatis. Nibh mauris cursus mattis molestie. Odio aenean sed adipiscing diam donec adipiscing. Ultricies tristique nulla aliquet enim. Neque viverra justo nec ultrices dui sapien. At augue eget arcu dictum varius duis at. Nunc eget lorem dolor sed viverra ipsum nunc.\n\nTortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Ut lectus arcu bibendum at varius. Blandit volutpat maecenas volutpat blandit aliquam etiam. Dolor sit amet consectetur adipiscing. Eget velit aliquet sagittis id consectetur purus. Pellentesque nec nam aliquam sem et tortor consequat id. Condimentum mattis pellentesque id nibh tortor id. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Elementum eu facilisis sed odio morbi quis commodo. Non enim praesent elementum facilisis leo. Nulla facilisi morbi tempus iaculis urna. Ornare arcu odio ut sem. Accumsan sit amet nulla facilisi morbi tempus. Turpis massa tincidunt dui ut. Neque gravida in fermentum et. Euismod in pellentesque massa placerat duis ultricies lacus sed turpis. Arcu dictum varius duis at consectetur.", "../../assets/imgs/img4.jpg"),
    new Chapter(5, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Ut aliquam purus sit amet luctus venenatis lectus. Sed risus ultricies tristique nulla aliquet. Quam vulputate dignissim suspendisse in est ante in nibh. Volutpat commodo sed egestas egestas. Fames ac turpis egestas integer. Purus in mollis nunc sed id semper risus in. Id aliquet risus feugiat in ante metus dictum. At tellus at urna condimentum mattis pellentesque id nibh tortor. Nec ullamcorper sit amet risus nullam eget felis eget. Congue quisque egestas diam in arcu. Lacus sed turpis tincidunt id aliquet risus feugiat in. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Neque vitae tempus quam pellentesque nec nam aliquam./n/nDuis tristique sollicitudin nibh sit amet commodo nulla facilisi. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Suspendisse faucibus interdum posuere lorem ipsum dolor. Interdum posuere lorem ipsum dolor sit. Cursus eget nunc scelerisque viverra mauris. Lectus nulla at volutpat diam ut venenatis tellus in metus. Tempus imperdiet nulla malesuada pellentesque. Porttitor lacus luctus accumsan tortor posuere. Neque volutpat ac tincidunt vitae semper quis lectus. Ut pharetra sit amet aliquam id diam maecenas ultricies mi. Mauris augue neque gravida in. Ante in nibh mauris cursus.", "../../assets/imgs/img5.jpg"),
    
];
  currentChapter : Chapter
  chapterNum : number
  nextNum : Number
  constructor(private route:ActivatedRoute) { }

  ngOnInit() {
    this.chapterNum = parseInt(this.route.snapshot.paramMap.get('id'));
    this.nextNum = this.chapterNum+1;
    this.currentChapter = this.chapters.find((a) => a.number == this.chapterNum);
  }

}
